version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Test
          command: ./test.sh

  integrationtest:
    docker:
      - image: loffek/testrunner-client:v0.1
        auth:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_PWD
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build image
          command: |
            docker build --rm=false -t loffek/serviceb .

      - deploy:
          name: Publish to DockerHub
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag loffek/serviceb $DOCKER_HUB_USER_ID/serviceb:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/serviceb:$CIRCLE_SHA1

      - deploy:
          name: Integration test
          command: |
            integrationtest --token=CIRCLE_API_TOKEN --build_args SERVICE_B_TAG=$CIRCLE_SHA1

workflows:
  version: 2
  build_and_integrationtest:
    jobs:
      - build
      - integrationtest
  just_build:
    jobs:
      - build
  just_integration_test:
    jobs:
      - integrationtest
