version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Test
          command: ./test.sh

  integrationtest:
    docker:
      - image: loffek/testrunner-client:v0.1
        auth:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_PWD

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Login
          command: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD

      - run:
          name: Build
          command: docker build --rm=false -t loffek/serviceb .

      - deploy:
          name: Publish Test Image
          command: |
            docker tag loffek/serviceb $DOCKER_HUB_USER_ID/serviceb:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/serviceb:$CIRCLE_SHA1

      - deploy:
          name: Integration test
          command: |
            integrationtest \
              --token=$CIRCLE_API_TOKEN \
              --build_parameters SERVICE_B_TAG=$CIRCLE_SHA1

      - deploy:
          name: Publish Release Image to DockerHub
          command: |
            if [ $CIRCLE_BRANCH = master ]; then
              docker tag loffek/serviceb $DOCKER_HUB_USER_ID/serviceb:master
              docker push $DOCKER_HUB_USER_ID/serviceb:master
            else
              echo "Branch is not master - skipping."
            fi

workflows:
  version: 2
  build_and_integrationtest:
    jobs:
      - build
      - integrationtest
